### ISSUE TITLE
tex格式不适用浏览器阅读

### ISSUE THREAD

**Issue by csyking** [ExtremeMart/DeepLearningBook-CN#28]
tex格式浏览器直接打开格式错乱，不知道是否可以用md格式编辑？

**Comment by extreme-assistant** [comment]
你需要下载一个latex的文件来打开tex 进行编辑~

**Comment by ysh329** [comment]
若是想要安装TeX软件，
在Linux平台上，你可以参考这个：http://www.oschina.net/question/12_63776?sort=default&p=2#answers
如果是Win平台，你可以参考这个：http://jingyan.baidu.com/article/db55b609950b154ba30a2fcb.html
